name: acme-zalgo
version: 0.1.3.0
license: MIT
git: https://github.com/Eisfunke/zalgo
author: anton@ekblad.cc
maintainer: nicolas@eisfunke.com

synopsis: A somewhat flexible Zalgo̐ te̳͜x̥̖̉̓͞t̍̌̔ ̀̃t̴̢̞̜͓̝r̶̬̆̂̒͟á̧̡͎͔̯̰̕n̹̾̓ͬͦ̍͘ṡ̢͓͉ͮ͆l̠̖̹̗̳̖̽̌ͤ͞a͚̭͙̹̲ͭͩt͈͐o̢̭͇͍̟͐ͬ̾ͪ͜r͇.̸̅ͭ̐̀̊ͨ͛
category: Acme

dependencies:
  - base
  - array
  - random

extra-doc-files:
  - README.md

library:
  source-dirs: src
  ghc-options:
    - -Wall
